# External repositories managed by chezmoi

["bin/scripts"]
    type = "git-repo"
    url = "git@git.sr.ht:~bgr/qol-scripts"
    refreshPeriod = "168h"  # Pull updates weekly

["bin/scripts".pull]
    args = ["--ff-only"]

["bin/scripts".clone]
    args = ["--depth", "1"]
